/**
 * Non-destructive migration from sub-project A schema to v0.1.
 *
 * For every existing `interviews/{id}` doc:
 *   - Create a corresponding `templates/{newId}` doc with role/level/JD-equivalent fields.
 *     The interview doc didn't have a JD, so we use questions as a proxy.
 *
 * For every existing `feedback/{id}` doc:
 *   - Create a corresponding `reports/{interviewId}` doc with shape-translated fields
 *     (recommendation defaults to 'inconclusive' since legacy schema didn't have one).
 *
 * Legacy collections are NOT deleted. After verifying v0.1 in production, a separate
 * cleanup script can drop them.
 *
 * Run with: `npx tsx scripts/migrate-v0.1.ts`
 */
import { db } from "../firebase/admin";

async function main() {
  console.log("Starting v0.1 migration...");

  const interviewsSnap = await db.collection("interviews").get();
  console.log(`Found ${interviewsSnap.size} legacy interviews`);

  let templatesCreated = 0;
  for (const idoc of interviewsSnap.docs) {
    const i = idoc.data() as {
      role?: string;
      level?: string;
      type?: string;
      questions?: string[];
      userId?: string;
      createdAt?: string;
    };

    const existing = await db
      .collection("templates")
      .where("legacyInterviewId", "==", idoc.id)
      .limit(1)
      .get();
    if (!existing.empty) continue;

    const tref = db.collection("templates").doc();
    await tref.set({
      id: tref.id,
      hrUid: i.userId ?? "legacy",
      title: `${i.role ?? "Legacy"} (migrated)`,
      role: i.role ?? "Engineer",
      level: i.level ?? "Mid",
      jobDescription: `Legacy interview migrated from interviews/${idoc.id}. No JD captured.`,
      questionsBase: i.questions ?? [],
      rubricsBase: [],
      status: "archived" as const,
      legacyInterviewId: idoc.id,
      createdAt: i.createdAt ?? new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });
    templatesCreated++;
  }
  console.log(`Created ${templatesCreated} templates from legacy interviews`);

  const feedbackSnap = await db.collection("feedback").get();
  console.log(`Found ${feedbackSnap.size} legacy feedback docs`);

  let reportsCreated = 0;
  for (const fdoc of feedbackSnap.docs) {
    const f = fdoc.data() as {
      interviewId: string;
      totalScore: number;
      categoryScores: Array<{ name: string; score: number; comment: string }>;
      strengths: string[];
      areasForImprovement: string[];
      finalAssessment: string;
      createdAt?: string;
    };
    const reportRef = db.collection("reports").doc(f.interviewId);
    const existing = await reportRef.get();
    if (existing.exists) continue;

    await reportRef.set({
      sessionId: f.interviewId,
      generatedAt: f.createdAt ?? new Date().toISOString(),
      totalScore: f.totalScore,
      categoryScores: f.categoryScores,
      strengths: f.strengths,
      areasForImprovement: f.areasForImprovement,
      finalAssessment: f.finalAssessment,
      recommendation: "inconclusive" as const,
      recommendationReasoning:
        "Legacy report — recommendation tier was not generated by the original pipeline.",
      rubricCoverage: {},
    });
    reportsCreated++;
  }
  console.log(`Created ${reportsCreated} reports from legacy feedback`);
  console.log("Migration complete.");
}

main().then(() => process.exit(0)).catch((e) => {
  console.error(e);
  process.exit(1);
});
